CREATE DATABASE IF NOT EXISTS hs_user CHARACTER SET utf8 COLLATE utf8_spanish_ci;
CREATE DATABASE IF NOT EXISTS hs_role CHARACTER SET utf8 COLLATE utf8_spanish_ci;
CREATE DATABASE IF NOT EXISTS hs_nourishment CHARACTER SET utf8 COLLATE utf8_spanish_ci;
CREATE DATABASE IF NOT EXISTS hs_consumption CHARACTER SET utf8 COLLATE utf8_spanish_ci;
CREATE DATABASE IF NOT EXISTS hs_category CHARACTER SET utf8 COLLATE utf8_spanish_ci;
