server:
  port: 8085

spring:
  application:
    name: security

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

application:
  jwt:
    secretKey: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 1
