server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///E:/workspace/Java/home-stuff-ms-config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/