server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Kirenai/home-stuff-ms-config-server
          username: ${GITHUB_USERNAME:}
          password: ${GITHUB_TOKEN:}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/